spring:
  application:
    name: tlias-web-management
  #   数据库的连接信息
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tlias
    username: root
    password: 1234
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启了驼峰映射开关
    map-underscore-to-camel-case: true